config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # get "/login", to "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/map", to: "maps#index"

  resources :users, except: [:destroy]
  resources :accidents, except: [:create, :update, :destroy]
end

app/models/accident.rb
class Accident < ApplicationRecord
  belongs_to :user

  enum status: {waiting: 0, processing: 1, done: 2}

  scope :order_desc, ->{order created_at: :desc}
  scope :user_exist, ->(user_id) {where("user_id = ?", user_id)}
  scope :waiting_or_processing, ->{where("status != ?", 2)}
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  attr_accessor :remember_token

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def remember
    self.remember_token = Admin.new_token
    update_attributes remember_digest: Admin.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum gender: {male: 0, female: 1, other: 2}

  has_many :accidents, dependent: :destroy

  scope :phone_is, ->(phone){where "phone == ?", phone}

  validates :email, presence: true, length: {maximum: 255},
    uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: 50}
  validates :phone, presence: true
  validates :gender, presence: true
  validates :blood_group, presence: true
  validates :helmet_id, presence: true
  validates :phone_emergency, presence: true
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController
  before_action :find_user, only: :new
  before_action :find_accident, except: [:index, :new]
  before_action :load_status, only: [:show, :update]

  def index
    @accidents = Accident.order_desc.paginate page: params[:page], per_page: 10
  end

  def new
    @accident = Accident.waiting_or_processing.user_exist(@user.id).first
    if (@accident.blank?)
      @accident = Accident.new accident_params
      if @accident.save
        redirect_to map_path
      end
    else
      if @accident.update_attributes accident_params
        redirect_to map_path
      end
    end
  end

  def show

  end

  def edit
    if @accident.update_attributes accident_update_params
      flash[:success] = t "flash.update_accident_success"
      redirect_to accident_path(@accident)
    else
      render :show
    end
  end

  private
  def accident_params
    params.permit(:lati, :longti).merge user_id: @user.id
  end

  def accident_update_params
    params.permit(:status, :description)
  end

  def find_user
    @user = User.find_by helmet_id: params[:ID]
    if @user.nil?
      flash[:danger] = t "flash.user_not_found"
      redirect_to users_path
    end
  end

  def find_accident
    @accident = Accident.find_by id: params[:id]
    if @accident.nil?
      flash[:danger] = "flash.accident_not_found"
      redirect_to accidents_path
    end
  end

  def load_status
    @accidents = Accident.statuses.keys
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = t "flash.must_logged_in"
      redirect_to root_path
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @accident = Accident.waiting_or_processing
    @hash = Gmaps4rails.build_markers(@accident) do |accident, marker|
      marker.lat accident.lati
      marker.lng accident.longti
      marker.picture({
        :url => view_context.image_path("logo2.png"),
        :width   => 32,
        :height  => 32
        })
      marker.infowindow render_to_string(:partial => "accidents/infowindow",
        :locals => { :accident => accident})
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by email:params[:session][:email].downcase
    if admin && admin.authenticate(params[:session][:password])
      log_in admin
      params[:session][:remember_me] == "1" ? remember(admin) : forget(admin)
      redirect_to users_path
    else
      flash.now[:danger] = t "flash.invalid_login"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :find_user, except: [:index, :new, :create]
  before_action :load_gender, except: [:index, :destroy]

  def index
    @users = if user_phone = params[:phone]
      User.phone_is user_phone
    else
      User.all
    end.paginate page: params[:page], per_page: 10
  end

  def new
     @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:info] = t "flash.add_user_success"
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "flash.update_user_success"
      redirect_to users_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :phone, :gender, :blood_group,
      :helmet_id, :phone_emergency, :description
  end

  def find_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = t "flash.user_not_found"
      redirect_to users_path
    end
  end

  def load_gender
    @genders = User.genders.keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = " "
    base_title = t "layouts.base_title"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in admin
    session[:admin_id] = admin.id
  end

  def current_admin
    if admin_id = session[:admin_id]
      @current_admin ||= Admin.find_by id: admin_id
    elsif admin_id = cookies.signed[:admin_id]
      admin = Admin.find_by id: admin_id
      if admin && admin.authenticated?(:remember, cookies[:remember_token])
        log_in admin
        @current_admin = admin
      end
    end
  end

  def remember admin
    admin.remember
    cookies.permanent.signed[:admin_id] = admin.id
    cookies.permanent[:remember_token] = admin.remember_token
  end

  def forget admin
    admin.forget
    cookies.delete :admin_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_admin
    session.delete :admin_id
    @current_admin = nil
  end

  def logged_in?
    current_admin.present?
  end
end

app/views/accidents/_accident.html.erb
<tr>
  <td><%= accident.user.helmet_id %></td>
  <td><%= accident.user.name %></td>
  <td><%= accident.user.phone %></td>
  <td><%= accident.user.gender %></td>
  <td><%= l accident.created_at.in_time_zone(t "time.zone") %></td>
  <td><%= accident.status %></td>

  <td>
    <%= link_to t("accident.index.detail"), accident_path(accident), class: "btn btn-info" %>
  </td>
  <td>
    <%= link_to t("accident.index.delete"), accident_path(accident), class: "btn btn-danger",
      method: :delete, data: {confirm: t("data.confirm")} %>
  </td>
</tr>

app/views/accidents/_accident_detail.html.erb
<%= form_tag edit_accident_path(@accident), method: :get do %>
  <table class="table table-responsive receiver_infomation">
    <tr>
      <th><%= t "accidents.index.accident_time" %></th>
      <td><%= l @accident.created_at.in_time_zone(t "time.zone") %></td>
    </tr>
     <tr>
      <th><%= label_tag t("accidents.index.status") %></th>
      <td><%= select_tag :status, options_for_select(@accidents, @accident.status),
          class: "form-control" %></td>
    </tr>
    <tr>
      <th><%= label_tag t("accidents.index.description") %></th>
      <td><%= text_area_tag :description, @accident.description ,class: "form-control" %>
        <%= submit_tag "Update", class: "btn btn-primary" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/accidents/_infowindow.html.erb
<%= t "accidents.index.name" %>: <%= accident.user.name %></br>
<%= t "accidents.index.phone" %>: <%= accident.user.phone %></br>
<%= t "accidents.index.gender" %>: <%= accident.user.gender %></br>
<%= t "accidents.index.accident_time" %>:
  <%= l accident.created_at.in_time_zone(t "time.zone") %></br>
<%= t "accidents.index.status" %>: <%= accident.status %></br>
<%= link_to t("accidents.index.detail"), accident_path(accident) %>

app/views/accidents/_user_information.html.erb
<table class="table table-responsive receiver_infomation">
  <tr>
    <th><%= t "users.index.name" %></th>
    <td><%= @accident.user.name %></td>
  </tr>
  <tr>
    <th><%= t "users.index.phone" %></th>
    <td><%= @accident.user.phone %></td>
  </tr>
  <tr>
    <th><%= t "users.index.gender" %></th>
    <td><%= @accident.user.gender %></td>
  </tr>
  <tr>
    <th><%= t "users.index.blood_group" %></th>
    <td><%= @accident.user.blood_group %></td>
  </tr>
  <tr>
    <th><%= t "users.index.phone_emergency" %></th>
    <td><%= @accident.user.phone_emergency %></td>
  </tr>
  <tr>
    <th><%= t "users.index.description" %></th>
    <td><%= @accident.user.description %></td>
  </tr>
</table>

app/views/accidents/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-responsive table-striped table-bordered">
      <thead>
        <tr>
          <th><%= t ".helmet" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".phone" %></th>
          <th><%= t ".gender" %></th>
          <th><%= t ".accident_time" %></th>
          <th><%= t ".status" %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @accidents %>
      </tbody>
    </table>
  </div>
  <div class="col-md-12 text-center">
    <%= will_paginate %>
  </div>
</div>

app/views/accidents/show.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading text-center"><%= t ".victim" %></div>
      <%= render "user_information" %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-info">
      <div class="panel-heading text-center"><%= t ".title" %></div>
      <%= render "accident_detail" %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="index.html">
                <h1>UNIQUE TEAM</h1>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to t(".home"), map_path%></li>
            <li><%= link_to t(".user"), users_path %></li>
            <li><%= link_to t(".accident"), accidents_path %></li>
            <li><%= link_to t(".logout"), logout_path,
              method: "delete" %></li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<script type="text/javascript">
    $('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');
</script>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
  </head>
    <% if logged_in? %>
      <body>
        <%= render "layouts/header" %>
        <div class="container no-margin-top">
          <% flash.each do |message_type, message| %>
            <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
          <% end %>
          <%= yield %>
        </div>
      </body>
    <% else %>
      <body class="login">
        <div class="container">
          <% flash.each do |message_type, message| %>
            <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
          <% end %>
          <%= yield %>
        </div>
      </body>
    <% end %>
</html>

app/views/maps/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyAjsc1tn7rw0aBLMbo0FEPGWRbwHbxHAdg"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<script>
$(document).on('turbolinks:load', function(){
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
});
</script>

<div style="width: 100%;"">
  <div id="map" style="width: 1170px; height: 500px"></div>
</div>


<script>
  var time = new Date().getTime();
  $(document.body).bind("mousemove keypress", function(e) {
    time = new Date().getTime();
  });
  function refresh() {
    if(new Date().getTime() - time >= 10000)
      window.location.reload(true);
    else
      setTimeout(refresh, 10000);
  }
  setTimeout(refresh, 10000);
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_contain" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url_path) do |f| %>
  <div class="form-group">
    <%= render "shared/error_messages", object: f.object %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.name") %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.email") %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.phone") %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.gender") %>
    <%= f.select :gender, options_for_select(@genders),{},
        class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.blood_group") %>
    <%= f.text_field :blood_group, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.helmet") %>
    <%= f.text_field :helmet_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.phone_emergency") %>
    <%= f.text_field :phone_emergency, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t("users.index.description") %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_search_form.html.erb
<%= form_tag users_path, method: :get do %>
  <div class="input-group">
    <%= text_field_tag :phone, params[:phone], class: "form-control",
      placeholder: t(".placeholder_phone") %>
    <span class="input-group-btn">
      <%= submit_tag t(".search"), class: "btn btn-default" %>
    </span>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.helmet_id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.phone %></td>
  <td><%= user.gender %></td>
  <td><%= user.blood_group %></td>
  <td><%= user.phone_emergency %></td>
  <td>
    <%= link_to t(".edit"), edit_user_path(user), class: "btn btn-info" %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :url_path, user_path(@user) %>
<% provide :button_text, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row margin-bottom-10">
  <div class="col-md-6">
    <%= link_to t(".add_user"), new_user_path, class: "btn btn-primary" %>
  </div>
  <div class="col-md-6 pull-right">
    <%= render "search_form" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-responsive table-striped table-bordered">
      <thead>
        <tr>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
          <th><%= t ".phone" %></th>
          <th><%= t ".gender" %></th>
          <th><%= t ".blood_group" %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>
  <div class="col-md-12 text-center">
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :url_path, users_path %>
<% provide :button_text, t(".title") %>
<h1><%= t ".title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>